/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InformatorJava;

/**
 *
 * @author Petr
 */
public class DetailedArticle extends javax.swing.JDialog {
    /**
     * Creates new form DetailedArticle
     */
    public DetailedArticle(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        contentStringTextArea.setEditable(false);
        contentStringTextArea.setLineWrap(true);
    }

    public void setStrings(Article article){
        String content = article.getContent();
        content = content.replaceAll("</p>", "\n\n");
        content = content.replaceAll("<p>", "");
        headingString.setText(article.getTitle());
        contentStringTextArea.setText(content);
        publishedString.setText("Stav: "+((article.isPublished())?"PUBLIKOVÁNO":"NEPUBLIKOVÁNO"));
        categoryString.setText("Kategorie: "+article.getCategory().toUpperCase());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headingString = new javax.swing.JLabel();
        publishedString = new javax.swing.JLabel();
        closeBtn = new javax.swing.JButton();
        categoryString = new javax.swing.JLabel();
        contentString = new javax.swing.JScrollPane();
        contentStringTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detailní zobrazení článku");

        headingString.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        headingString.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headingString.setText("Nadpis");

        publishedString.setBackground(new java.awt.Color(255, 255, 255));
        publishedString.setForeground(new java.awt.Color(0, 0, 0));
        publishedString.setText("Published");
        publishedString.setOpaque(true);

        closeBtn.setText("Zavřít");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        categoryString.setBackground(new java.awt.Color(255, 255, 255));
        categoryString.setForeground(new java.awt.Color(0, 0, 0));
        categoryString.setText("Category");
        categoryString.setOpaque(true);

        contentStringTextArea.setColumns(20);
        contentStringTextArea.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        contentStringTextArea.setRows(5);
        contentStringTextArea.setAutoscrolls(false);
        contentString.setViewportView(contentStringTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(closeBtn))
                    .addComponent(headingString, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(publishedString)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(categoryString))
                            .addComponent(contentString, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headingString)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentString, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(publishedString)
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(categoryString)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(closeBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailedArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailedArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailedArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailedArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DetailedArticle dialog = new DetailedArticle(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    public void showDialog() {
		this.setVisible(true);
		return;
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel categoryString;
    private javax.swing.JButton closeBtn;
    private javax.swing.JScrollPane contentString;
    private javax.swing.JTextArea contentStringTextArea;
    private javax.swing.JLabel headingString;
    private javax.swing.JLabel publishedString;
    // End of variables declaration//GEN-END:variables
}
